#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscale[-1]
	commit ucitrack
EOF
	chmod 755 /etc/init.d/tailscale >/dev/null 2>&1
	/etc/init.d/tailscale enable >/dev/null 2>&1

rm -f /tmp/luci-indexcache
exit 0
